
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lzisyhriihicfavgndeb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6aXN5aHJpaWhpY2ZhdmduZGViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMjIyNjUsImV4cCI6MjA2MTY5ODI2NX0.d9IhQZN_-DGhKfEy8Dw1CIaUmrWQq2dp_nIXmFtmXMc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
