// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppupewiaqxedbfthuicp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwdXBld2lhcXhlZGJmdGh1aWNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMjg3NjMsImV4cCI6MjA2MTcwNDc2M30.eOY99dXeRUignH006_MrnntQcyYXryzlAlOjtUvbZo8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
